name: first

on:
    workflow_dispatch:
env:
    ENV: ${{ vars.ENV }}
    ARG1: ${{ vars.ARG1 }}
    ARG2: ${{ vars.ARG2 }}
    ARG3: ${{ vars.ARG3 }}

jobs:
    run_python:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'

            - name: Install dependencies
              run: |
                echo "ENVS=${ARG1}/${ARG2}/${ARG3}" > "${GITHUB_ENV}"
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: check env
              run: |
                echo "${GITHUB_ENV}"
                echo "${ENVS}"

    job2:
        runs-on: ubuntu-latest
        needs: run_python
        steps:
            - name: Print environment variables
              run: |
                echo "ENVS=${ARG1}/${ARG2}/${ARG3}"

    call_wf:
        needs: job2
        uses: ./.github/workflows/second.yaml
        with:
            ENV: ${{ vars.ENV }}
            ARG1: ${{ vars.ARG1 }}
            ARG2: ${{ vars.ARG2 }}
            ARG3: ${{ vars.ARG3 }}
        secrets:
            SECRET1: "${{ secrets.SECRET1 }}"
            SECRET2: "${{ secrets.SECRET2 }}"
            SECRET3: "${{ secrets.SECRET3 }}"

    check_output:
        runs-on: ubuntu-latest
        needs: call_wf
        steps:
            - name: Print output
              run: |
                echo "Return value from second workflow: ${{ needs.call_wf.outputs.RET_VAL }}"
            
            - name: check directory
              run: |
                echo "Directory contents:"
                ls -la "${{ needs.call_wf.outputs.RET_VAL }}"
                echo "Config file content:"
                cat test/config.json