name: first

on:
    workflow_dispatch:
env:
    ENV: ${{ vars.ENV }}
    ARG1: ${{ vars.ARG1 }}
    ARG2: ${{ vars.ARG2 }}
    ARG3: ${{ vars.ARG3 }}
    SECRET1: ${{ secrets.SECRET1 }}
    SECRET2: ${{ secrets.SECRET2 }}
    SECRET3: ${{ secrets.SECRET3 }}
jobs:
    run_python:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'

            - name: Install dependencies
              run: |
                echo "ENVS=${ARG1}/${ARG2}/${ARG3}" > "${GITHUB_ENV}"
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: check env
              run: |
                echo "${GITHUB_ENV}"
                echo "${ENVS}"

    job2:
        runs-on: ubuntu-latest
        needs: run_python
        steps:
            - name: Print environment variables
              run: |
                echo "ENVS=${ARG1}/${ARG2}/${ARG3}"

    call_wf:
        uses: ./second.yaml
        with:
            ENV: "${ENV}"
            ARG1: "${ARG1}"
            ARG2: "${ARG2}"
            ARG3: "${ARG3}"
        secrets:
            SECRET1: "${SECRET1}"
            SECRET2: "${SECRET2}"
            SECRET3: "${SECRET3}"