name: first

on:
    workflow_dispatch:

env:
    AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
    fetch_rgs:
        runs-on: ubuntu-latest
        outputs:
            rg_ids: ${{ steps.fetch_ids.outcomets.rg_ids }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.12'
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -r requirements.txt
            - name: fetch_ids
              id: fetch_ids
              run: |
                  rg_ids=$(python fetch_rgs.py)
                  echo "rg_ids<<EOF" >> "$GITHUB_OUTPUT"
                  echo ${rg_ids} >> "$GITHUB_OUTPUT"
                  echo "EOF" >> "$GITHUB_OUTPUT"


    call_wf:
        uses: ./.github/workflows/second.yaml
        needs: fetch_rgs
        with:
            rg_ids: ${{ needs.fetch_rgs.outputs.rg_ids }}
        secrets:
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}