name: first

on:
    workflow_dispatch:
env:
    ENV: ${{ vars.ENV }}
    ARG1: ${{ vars.ARG1 }}
    ARG2: ${{ vars.ARG2 }}
    ARG3: ${{ vars.ARG3 }}
    SECRET1: ${{ secrets.SECRET1 }}
    SECRET2: ${{ secrets.SECRET2 }}
    SECRET3: ${{ secrets.SECRET3 }}
jobs:
    run_python:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'

            - name: Install dependencies
              run: |
                echo "${ARG1}, ${ARG2}, ${ARG3}"
                echo "${SECRET1}, ${SECRET2}, ${SECRET3}"
                python -m pip install --upgrade pip
                pip install -r requirements.txt

