name: second
on:
    workflow_call:
        inputs:
            ENV:
                required: true
                type: string
            ARG1:
                required: true
                type: string
            ARG2:
                required: true
                type: string
            ARG3:
                required: true
                type: string
        secrets:
            SECRET1:
                required: true
            SECRET2:
                required: true
            SECRET3:
                required: true
        outputs:
            RET_VAL:
                description: 'Return value from the Python script'
                value: ${{ jobs.check_input.outputs.ret_val }}
jobs:
    check_input:
        runs-on: ubuntu-latest
        outputs:
            ret_val: ${{ steps.run_python.outputs.ret_val }}
        steps:
            - name: Print input variables
              id: run_python
              run: |
                ret_val=python run_python.py ${{ inputs.ARG1 }}
                echo $ret_val >> $GITHUB_OUTPUT