name: second
on:
    workflow_call:
        inputs:
            rg_ids:
                description: 'Resource Group IDs'
                required: true
                type: string
        secrets:
            AZURE_CLIENT_ID:
                description: 'Azure Client ID'
                required: true
            AZURE_CLIENT_SECRET:
                description: 'Azure Client Secret'
                required: true
            AZURE_TENANT_ID:
                description: 'Azure Tenant ID'
                required: true
            AZURE_SUBSCRIPTION_ID:
                description: 'Azure Subscription ID'
                required: true
jobs:
    get_rg_data:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                python -m pip install -r requirements.txt
            - name: Print input variables
              id: run_python
              run: |
                python get_rg_dat.py "${{ inputs.rg_ids }}"