name: second
on:
    workflow_call:
        inputs:
            rg_ids:
                description: 'Resource Group IDs'
                required: true
                type: string
        secrets:
            AZURE_CLIENT_ID:
                description: 'Azure Client ID'
                required: true
            AZURE_CLIENT_SECRET:
                description: 'Azure Client Secret'
                required: true
            AZURE_TENANT_ID:
                description: 'Azure Tenant ID'
                required: true
            AZURE_SUBSCRIPTION_ID:
                description: 'Azure Subscription ID'
                required: true

jobs:
    get_rg_data:
        env:
            rg_ids: ${{ inputs.rg_ids }}
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                python -m pip install -r requirements.txt
            - name: Print input variables
              id: run_python
              run: |
                # Ensure the input is a valid JSON string
                echo "Input RG IDs: $rg_ids"
                test=$(python get_rg_dat.py "${rg_ids}")
                echo $test